// src/views/register/stages/FinalConfirm.vue
<template>
  <div v-if="isPending">
    <p>Vytváření účtu...</p>
  </div>

  <div v-else-if="isError">
    <h1>Chyba</h1>
    <p>{{ error.message }}</p>
    <button @click="register">Zkusit znovu</button>
  </div>

  <div v-else>
    <h1>Úspěch</h1>
    <h2>Váš účet byl založen.</h2>
    <button class="primary" @click="onClick">Pokračovat</button>
  </div>
</template>

<script setup lang="ts">
import { onMounted } from 'vue'
import { useRouter } from 'vue-router'
import { useMutation } from '@tanstack/vue-query'
import { postRegister } from '@/api/account'
import { accountStore } from '@/state/AccountStore'
import { registerStore } from '@/state/RegisterStore'
import type { SignUpRequest } from '@/api/types/auth'

const router = useRouter()

const { mutate, isError, isPending, data, error } = useMutation({
  mutationFn: (data: SignUpRequest) => postRegister(data)
})

// Function to call the registration mutation
const register = () => {
  mutate({
    email: registerStore.email,
    firstName: registerStore.name,
    lastName: registerStore.surname,
    nickname: registerStore.nickname,
    password: registerStore.password,
    consent: true // the user can't reach this point without consenting
  })
}

onMounted(() => {
  register()
})

const onClick = () => {
  router.replace('/');
  registerStore.resetStage();
  if (data.value) {
    accountStore.login(data.value)
  }
}
</script>

// src/screens/popup/register/finalConfirm.tsx
import { postRegister } from "@/api/account";
import { useAccount, useRegisterState } from "@/state/store";
import { SignUpRequest } from "@/types/api/auth";
import { useMutation } from "@tanstack/react-query";
import { useNavigate } from "react-router";
import { useEffectOnce } from "react-use";

export default function Register1() {
  const navigate = useNavigate();
  const registerInfo = useRegisterState();
  const resetStage = useRegisterState(state => state.resetStage);
  const setSession = useAccount(state => state.login);

  const mutation = useMutation({
    mutationFn: (registerInfo: SignUpRequest) => postRegister(registerInfo)
  })

  const register = () => mutation.mutate(registerInfo);

  useEffectOnce(() => {
    register();
  })

  const onClick = () => {
    navigate("/");
    resetStage();
    setSession(mutation.data!);
  }

  if (mutation.isPending) {
    return <p>Vytváření účtu...</p>;
  }

  if (mutation.error) {
    return (
      <div>
        <h1>Chyba</h1>
        <p>{mutation.error.message}</p>
        <button onClick={() => register}>Zkusit znovu</button>
      </div>
    );
  }

  return (
    <div>
      <h1>Úspěch</h1>
      <h2>Váš účet byl založen.</h2>
      <button onClick={onClick}>Pokračovat</button>
    </div>
  );
}
