// src/views/register/stages/PersonalInfo.vue
<script setup lang="ts">
import { ref } from 'vue';
import { registerStore } from '@/state/RegisterStore'

const name = ref('');
const surname = ref('');
const nickname = ref('');

function handleSubmit() {
  registerStore.setName(name.value);
  registerStore.setSurname(surname.value);
  registerStore.setNickname(nickname.value);
  registerStore.nextStage();
}
</script>

<template>
  <div>
    <form @submit.prevent="handleSubmit" class="flex flex-col">
      <input v-model="name" name="name" type="text" placeholder="Jméno" />
      <input v-model="surname" name="surname" type="text" placeholder="Příjmení" />
      <input v-model="nickname" name="nickname" type="text" placeholder="Přezdívka" />
      <button class="primary p-2 m-2" type="submit">Pokračovat</button>
    </form>
  </div>
</template>

// src/screens/popup/register/personalInfo.tsx
import { useRegisterState } from "@/state/store";

export default function Register1() {

  const setName = useRegisterState(state => state.setName);
  const setSurname = useRegisterState(state => state.setSurname);
  const setNickname = useRegisterState(state => state.setNickname);
  const nextStage = useRegisterState(state => state.nextStage);

  const handleRegister = (formData: FormData) => {
    const name = formData.get("name");
    const surname = formData.get("surname");
    const nickname = formData.get("nickname");

    setName(name as string);
    setSurname(surname as string);
    setNickname(nickname as string);
    nextStage();
  };

  return (
    <div>
      <form className="flex flex-col" action={handleRegister}>
        <input name="name" type="text" placeholder="Jméno" />
        <input name="surname" type="text" placeholder="Příjmení" />
        <input name="nickname" type="text" placeholder="Přezdívka" />
        <button className="primary p-2 m-2" type="submit">Pokračovat</button>
      </form>
    </div>
  );
}
