// src/features/Account/screens/register-stages/PersonalInfo.vue
<script setup lang="ts">
import { registerStore } from '@/features/Account/state/RegisterStore'

</script>

<template>
  <h1>Osobní informace</h1>
  <form class="flex flex-col gap-y-4" @submit.prevent="registerStore.nextStage">
    <div class="flex flex-col gap-y-1">
      <label for="name" class="block text-sm font-medium">Jméno</label>
      <input id="name" v-model="registerStore.name" type="text" required />
    </div>
    <div class="flex flex-col gap-y-1">
      <label for="surname" class="block text-sm font-medium">Příjmení</label>
      <input id="surname" v-model="registerStore.surname" type="text" required />
    </div>
    <div class="flex flex-col gap-y-1">
      <label for="nickname" class="block text-sm font-medium">Přezdívka (nepovinné)</label>
      <input id="nickname" v-model="registerStore.nickname" type="text" />
      <label for="nickname" class="text-wrap text-gray-600">Pokud nevyplníte přezdívku, na webu bude zobrazováno Vaše celé jméno.</label>
    </div>
    <button class="primary p-2 m-2" type="submit">Pokračovat</button>
  </form>
</template>

// src/screens/popup/register/personalInfo.tsx
import { useRegisterState } from "@/state/store";

export default function Register1() {

  const setName = useRegisterState(state => state.setName);
  const setSurname = useRegisterState(state => state.setSurname);
  const setNickname = useRegisterState(state => state.setNickname);
  const nextStage = useRegisterState(state => state.nextStage);

  const handleRegister = (formData: FormData) => {
    const name = formData.get("name");
    const surname = formData.get("surname");
    const nickname = formData.get("nickname");

    setName(name as string);
    setSurname(surname as string);
    setNickname(nickname as string);
    nextStage();
  };

  return (
    <div>
      <h1 className='text-2xl font-bold'>Zadejte vaše jméno, příjmení a zvolte s i přezdívku</h1>
      <form className="flex flex-col gap-y-2" action={handleRegister}>
        <input name="name" type="text" placeholder="Jméno" />
        <input name="surname" type="text" placeholder="Příjmení" />
        <input name="nickname" type="text" placeholder="Přezdívka" />
        <button className="primary p-2 m-2" type="submit">Pokračovat</button>
      </form>
    </div>
  );
}
