// src/screens/popup/register/location.tsx
import { useRegisterState } from "@/state/store";
import { useNavigate } from "react-router";

export default function Register1() {

  const nextStage = useRegisterState(state => state.nextStage);
  const setPostalCode = useRegisterState(state => state.setPostalCode);
  const setCity = useRegisterState(state => state.setCity);

  const handleRegister = (formData: FormData) => {
    const postalCode = formData.get("postalCode");
    const city = formData.get("city");

    setPostalCode(postalCode as string);
    setCity(city as string);

    nextStage();
  };

  return (
    <div>
      <h1>Kde se nacházíte?</h1>
      <form className="flex flex-col gap-y-2" action={handleRegister}>
        <input name="postalCode" type="number" placeholder="PSČ" />
        <input name="city" type="text" placeholder="Město" />
        <button className="primary p-2 m-2" type="submit">Pokračovat</button>
      </form>
    </div>
  );
}

// src/features/Account/screens/register-stages/Location.vue
<template>
  <h1>Kde se nacházíte?</h1>
  <div class="flex flex-col gap-y-4">
    <div class="flex flex-col gap-y-1">
      <label for="postalCode" class="block text-sm font-medium" >PSČ</label>
      <input id="postalCode" v-model="registerStore.postCode" name="postalCode" type="number" min="0" max="99999" />
      <p class="text-gray-600">Nepovinné. Tyto údaje budou použity k doručování novinek z vaší lokality.</p>
    </div>
    <div class="flex flex-col gap-y-1">
      <label for="city" class="block text-sm font-medium">Město</label>
      <LocationSearch id="city" v-model:text="registerStore.city" />
      <p class="text-gray-600">Nepovinné. Toto bude zobrazeno veřejně na vašem profilu.</p>
    </div>
    <button class="primary p-2 m-2" @click="registerStore.nextStage">Pokračovat</button>
  </div>
</template>

<script setup lang="ts">
import LocationSearch from '@/features/Map/components/LocationSearch.vue';
import { registerStore } from '@/features/Account/state/RegisterStore';
</script>
