// src/screens/popup/register/password.tsx
import { useRegisterState } from "@/state/store";

export default function Register1() {

  const nextStage = useRegisterState(state => state.nextStage);
  const setPassword = useRegisterState(state => state.setPassword);

  const handleRegister = (formData: FormData) => {
    const password = formData.get("password");
    const passwordAgain = formData.get("passwordAgain");

    if (password !== passwordAgain) {
      alert("Hesla se neshodují.");
      return;
    }

    setPassword(password as string);
    nextStage();
  };

  return (
    <div>
      <h1>Nastavte si heslo</h1>
      <form className="flex flex-col" action={handleRegister}>
        <input name="password" type="password" placeholder="Heslo" />
        <input name="passwordAgain" type="password" placeholder="Heslo znovu" />
        <button className="primary p-2 m-2" type="submit">Pokračovat</button>
      </form>
    </div>
  );
}

// src/features/Account/screens/register-stages/Password.vue
<script setup lang="ts">
import { ref } from 'vue';
import { registerStore } from '@/features/Account/state/RegisterStore';
import RevealablePasswordInput from '@/features/RevealablePasswordInput/components/RevealablePasswordInput.vue';

const password = ref('');
const passwordAgain = ref('');

const handleRegister = () => {
  if (password.value !== passwordAgain.value) {
    alert("Hesla se neshodují.");
    return;
  }

  registerStore.setPassword(password.value);
  registerStore.nextStage();
};
</script>

<template>
  <h1>Nastavte si heslo</h1>
  <form @submit.prevent="handleRegister" class="flex flex-col">
    <RevealablePasswordInput v-model="password" label="Heslo" />
    <RevealablePasswordInput v-model="passwordAgain" label="Heslo znovu" />
    <button class="primary p-2 m-2" type="submit">Pokračovat</button>
  </form>
</template>
