// src/views/nav/Navbar.vue
<script setup lang="ts">
import { ref, computed } from 'vue';
import { accountStore } from '@/state/AccountStore';

import { useQuery } from '@tanstack/vue-query';

import { getArticleCategories, type ArticleCategory, type Article } from '@/api/articles'

import Dropdown from '@/components/Dropdown.vue'
import AccountDropdown from '@/views/dropdown/account/AccountDropdown.vue';

import Upload from '@/icons/interface/icon-upload.svg';
import Notifications from '@/icons/interface/icon-notifications-empty.svg';
import List from '@/icons/interface/icon-list.svg';

import DropdownIcon from '@/icons/interface/dropdown.svg'
import MapIcon from '@/icons/interface/icon-map.svg'

const isMenuOpen = ref(false);

const { data: categories } = useQuery({
  queryKey: ["categories"],
  queryFn: async () => getArticleCategories()
})

</script>

<template>
  <nav class="w-full">
    <div class="flex justify-between gap-x-4 items-center h-16 bg-white rounded-4xl m-2 desktop:m-5 pr-4">
      <!-- Logo -->
      <div class="h-full flex flex-row items-center p-4 font-semibold rounded-4xl bg-[#fdfcdc] border-[#fdfcdc]">
        <PrefetchLink to="/vitejte">
          <img src="/logo.svg" alt="Logo" />
        </PrefetchLink>
      </div>

      <!-- Desktop navigation -->
      <div class="hidden desktop:flex justify-between items-center w-full">
        <ul class='flex flex-row gap-x-4 items-center'>
          <li>
            <PrefetchLink to="/" class='dropdown-item'>
              <MapIcon />
              Mapa
            </PrefetchLink>
          </li>

          <template v-if="accountStore.user">
            <li>
              <PrefetchLink to="/nahrat" class='dropdown-item'>
                <Upload />
                Nahrát
              </PrefetchLink>
            </li>
            <li>
              <PrefetchLink to="/ucet/sprava/moje-nahravky" class='dropdown-item'>
                <List />
                Moje záznamy
              </PrefetchLink>
            </li>
          </template>

          <Dropdown v-for="category in categories">
            <template #title class="flex flex-row items-center">
              {{ category.label }}
              <DropdownIcon />
            </template>

            <li
              v-for="article in category.articles"
            >
              <prefetch-link :to="`/informace/${article.id}`" class="dropdown-item !flex !flex-col">
                {{ article.name }}
                <span class="italic" v-if="article.description">
                  {{ article.description }}
                </span>
              </prefetch-link>
            </li>
          </Dropdown>
        </ul>

        <ul class="flex flex-row gap-x-4 items-center">
          <PrefetchLink to="/aplikace" class='button-primary py-2 px-4 max-sm:text-sm'>
            Stáhnout aplikaci
          </PrefetchLink>
          <li>
            <AccountDropdown v-if="accountStore.user" />
            <PrefetchLink v-else to="/ucet/vitejte" class="button-secondary py-2 px-4">
              Přihlásit se
            </PrefetchLink>
          </li>
        </ul>
      </div>
    </div>
  </nav>
</template>

<style scoped>

@reference "../../styles/main.css";

:deep(.dropdown-item) {
  @apply font-semibold flex flex-row items-center gap-x-1 px-5 py-2 hover:bg-gray-100 hover:border-0 rounded-xl;
}

nav {
  @apply fixed z-[9] drop-shadow-xl min-w-0 w-full;
}

</style>

// src/components/navbar.tsx
import { Link, useLocation } from "react-router";

import Upload from '@/assets/icon-upload.svg';
import List from '@/assets/icon-list.svg';
import NotificationsEmpty from '@/assets/icon-notifications-empty.svg';

import AccountDropdown from "@/components/account-drop";
import { useAccount } from "@/store";
import InfoDropdown from "./info-drop";

export default function Navbar() {

  const location = useLocation();
  const pathname = location.pathname;
  const session = useAccount(state => state.token);

  return (
    <nav className="bg-white rounded-4xl m-5 pr-10">
      <div className="flex justify-between items-center h-16">
        <div className='flex flex-row gap-x-8 items-center'>
          <Link to={'/'} className='font-semibold rounded-4xl bg-[#fdfcdc] p-2 border-[3px] border-[#fdfcdc]'>
            <div className="flex items-center">
              <img src="/logo.svg" />
            </div>
          </Link>
          <Link to="/add-recording" className='font-semibold flex flex-row gap-x-1 items-center'>
            <img src={Upload} />
            Nahrát
          </Link>
          <Link to="/account/my-recordings" className='font-semibold flex flex-row gap-x-1 items-center'>
            <img src={List} />
            Moje záznamy
          </Link>
          <Link to="/account/notifications" className='font-semibold flex flex-row gap-x-1 items-center'>
            <img src={NotificationsEmpty} />
            Oznámení
          </Link>
          <div className='font-semibold flex flex-row gap-x-1 items-center'>            
            <InfoDropdown />
          </div>
        </div>

        <div className="flex flex-row gap-x-4 items-center">
          <Link to="/application" className='button-primary py-2 px-4'>
              Stáhnout aplikaci
          </Link>
          { session
            ? <AccountDropdown />
            : <Link to="/auth/login" className="button-secondary py-2 px-4">Přihlásit se</Link>
          }
        </div>
      </div>
    </nav>
  );
}
