// src/views/Login.vue
<script setup lang="ts">
import { computed, ref } from 'vue';
import { useRouter } from 'vue-router';
import { useMutation } from '@tanstack/vue-query';
import { postLogin } from '@/api/account';
import { accountStore } from '@/state/AccountStore';

import LogoNoText from '@/assets/logo-no-text.svg';

const router = useRouter();

const email = ref('');
const password = ref('');

const mutation = useMutation({
  mutationFn: (loginInfo: { email: string; password: string }) => postLogin(loginInfo),
  onSuccess: (data) => {
    router.replace('/');
    accountStore.login(data);
  }
});

const loading = computed(() => mutation.isPending && !mutation.isIdle)

const handleLogin = () => {
  mutation.mutate({ email: email.value, password: password.value });
};

const navigateToRegister = () => {
  router.push("/auth/register");
};
</script>

<template>
  <div class="flex flex-col items-center gap-y-6 w-full">
    <img :src="LogoNoText" />
    <h1>Nářečí českých strnadů</h1>
    <span class="text-xl">Nahrávejte, mapujte, dobývejte</span>

    <div v-if="mutation.error.value">Chyba: {{ mutation.error.value }}</div>
    <div v-if="loading">Načítání...</div>
    <div v-else class="flex flex-col gap-y-2">
      <form class="flex flex-col w-full" @submit.prevent="handleLogin">
        <div class="flex flex-col gap-x-2 gap-y-4 w-full">
            <div>
              <label for="email" class="block text-sm font-medium mb-1">E-Mail</label>
              <input id="email" v-model="email" name="mail" type="email" placeholder="E-Mail" class="w-full p-2 border rounded" />
            </div>
            <div>
              <label for="password" class="block text-sm font-medium mb-1 flex flex-row justify-between"><span>Heslo</span><button>Zapomenuté heslo</button></label>
              <input id="password" v-model="password" name="pass" type="password" placeholder="Heslo" class="w-full p-2 border rounded" />
            </div>
        </div>
        <button class="primary p-2 m-2" type="submit" :disabled="loading">
          Přihlásit se
        </button>
      </form>
      <button class="secondary p-2" @click="navigateToRegister">
        Založit účet
      </button>
    </div>
  </div>
</template>

<style scoped>
/* Add component-specific styles here if needed */
</style>

// src/screens/popup/login.tsx
import { useAccount } from "@/state/store";
import { useState, useEffect } from "react";
import { useNavigate } from "react-router";
import PopupLayout from "@/layouts/layout-popup";
import { LoginRequest, Token } from "@/api/types/auth";
import { useMutation } from "@tanstack/react-query";
import { postLogin } from "@/api/account";
import { useEffectOnce } from "react-use";

import "@/styling/text.css"
import "@/styling/buttons.css"
import "@/styling/text-input.css"

const env = import.meta.env;

export default function Login() {
  const navigate = useNavigate();
  const login = useAccount(state => state.login);

  const mutation = useMutation({
    mutationFn: (loginInfo: LoginRequest) => postLogin(loginInfo),
    onSuccess: (data: Token) => {
      navigate('/');
      login(data);
    }
  })

  const handleLogin = (formData: FormData) => {
    const email = formData.get("mail") as string;
    const password = formData.get("pass") as string;
    mutation.mutate({ email, password })
  };

  return (
    <PopupLayout>
      <h1>Login</h1>

      <div className="flex flex-col items-center gap-y-4 w-full">
        {mutation.isPending && <div>Načítání...</div>}
        {mutation.error && <div>Chyba: {mutation.error.message}</div>}
        <form className="flex flex-col w-full" action={handleLogin}>
          <div className="flex flex-col gap-x-2 w-full">
            <input name="mail" type="email" placeholder="E-Mail" />
            <input name="pass" type="password" placeholder="Heslo" />
          </div>
          <button className="primary p-2 m-2" type="submit" disabled={mutation.isPending}>Přihlásit</button>
        </form>
        <button onClick={() => navigate("/auth/register")}>
          Nemáte ještě účet? Zaregistrujte se.
        </button>
      </div>
    </PopupLayout>
  );
}
