// src/views/MapOptions.vue
<template>
  <label for="map-mode-select">Vyberte podklad mapy:</label>
  
  <select id="map-mode-select" v-model="mapStore.mode">
    <option
      v-for="modeOption in ['basic', 'aerial', 'outdoor']"
      :key="modeOption"
      :value="modeOption"
    >
      {{ modeOption }}
    </option>
  </select>
</template>

<script setup lang="ts">
import { mapStore } from '@/state/MapStore';
</script>

// src/screens/popup/map-options.tsx
import PopupLayout from "@/layouts/layout-popup";
import { useMapState } from "@/state/store";

export default function MapOptions() {

  const setMode = useMapState((state) => state.setMode);
  const mode = useMapState((state) => state.mode);

  return (
    <PopupLayout>
      <label>Vyberte podklad mapy:</label>

      <select onChange={(e) => setMode(e.target.value as "aerial" | "basic" | "outdoor")} value={mode}>
        {
          (["basic", "aerial", "outdoor"] as Array<typeof mode>).map((modeOption) => (
            <option
              key={modeOption}
              value={modeOption}
            >
              {modeOption}
            </option>
          ))
        }
      </select>
    </PopupLayout>
  )
}
