// src/features/Account/screens/Register.vue
<script setup lang="ts">
import { shallowRef, watch } from 'vue'
import { defineAsyncComponent } from 'vue'
import { registerStore } from '@/features/Account/state/RegisterStore';
import SegmentedProgress from '@/features/SegmentedProgress/components/SegmentedProgress.vue';

const STAGE_MAPPING: Record<number, string> = {
  0: "Email",
  1: "PersonalInfo",
  2: "Location",
  3: "Password",
  4: "FinalConfirm",
  5: "Done"
};

const loadComponent = (stage: number) => defineAsyncComponent({
  loader: () => import(`./register-stages/${STAGE_MAPPING[stage]}.vue`)
});

const Component = shallowRef(loadComponent(registerStore.stage));

watch(() => registerStore.stage, (newStage) => {
  Component.value = loadComponent(newStage);
});

const stages = Object.keys(STAGE_MAPPING).length;

</script>

<template>
  <Component />
  <SegmentedProgress v-if="registerStore.stage != 0" :progress="registerStore.stage" :total-segments="stages" />
</template>

// src/screens/popup/register.tsx
import Loading from "@/components/loading";
import SegmentedProgressBar from "@/components/segmented-progress";
import PopupLayout from "@/layouts/layout-popup";
import { useRegisterState } from "@/state/store";
import React, { Suspense } from "react";

const componentFiles: Record<number, string> = {
  1: 'email',
  2: 'emailVerify',
  3: 'personalInfo',
  4: 'password',
  5: 'location',
  6: 'agree',
  7: 'finalConfirm'
};

export default function Register() {

  const stage = useRegisterState(state => state.stage);

  const Component = React.lazy(() => import(`./register/${componentFiles[stage]}.tsx`));

  const totalSegments = React.useMemo(() => Object.keys(componentFiles).length, []);

  return (
    <PopupLayout>
      <h1 className='text-2xl font-bold'>Registrace</h1>
      <Suspense fallback={<Loading />}>
        <Component />
        <SegmentedProgressBar totalSegments={totalSegments} progress={stage} />
      </Suspense>
    </PopupLayout>
  );

};
