// src/components/navbar/dropdowns/dropdown.tsx
import { useState, useEffect, useRef } from 'react';
import { useSlot } from "@beqa/react-slots";
import InfoIcon from '@/assets/icon-info.svg';
import InfoDropdownItems from './info-list-items';
import FormalStuff from './formal-stuff';

export default function Dropdown({ children }) {
  
  const { slot } = useSlot(children);

  const [isOpen, setIsOpen] = useState(false);
  const dropdownRef = useRef<HTMLDivElement>(null);

  // Handle clicking outside to close the dropdown
  useEffect(() => {
    function handleClickOutside(event: MouseEvent) {
      if (dropdownRef.current && !dropdownRef.current.contains(event.target as Node)) {
        setIsOpen(false);
      }
    }
    
    document.addEventListener('mousedown', handleClickOutside);
    return () => {
      document.removeEventListener('mousedown', handleClickOutside);
    };
  }, []);

  // Handle link clicks to close the dropdown
  const handleLinkClick = () => {
    setIsOpen(false);
  };

  return (
    <div 
      className="relative" 
      ref={dropdownRef}
    >
      <button 
        className="flex items-center focus:outline-none" 
        onMouseEnter={() => setIsOpen(true)}
      >
        <slot.title />
      </button>
      {isOpen && (
        <ul 
          className="absolute left-0 mt-2 w-40 z-[calc(1e12)] bg-white border border-gray-200 rounded shadow-lg"
          onMouseLeave={handleLinkClick}
          onClick={handleLinkClick}
        >
          <slot.default />
        </ul>
      )}
    </div>
  );
}

// src/components/generic/Dropdown.vue
<script setup lang="ts">
import { ref, onMounted, onBeforeUnmount } from 'vue';

const isOpen = ref(false);
const dropdownRef = ref(null);

function open() {
  isOpen.value = true;
}

function close() {
  isOpen.value = false;
}

function handleClickOutside(event) {
  if (dropdownRef.value && !dropdownRef.value.contains(event.target)) {
    close();
  }
}

onMounted(() => {
  document.addEventListener('mousedown', handleClickOutside);
});

onBeforeUnmount(() => {
  document.removeEventListener('mousedown', handleClickOutside);
});
</script>

<template>
  <div ref="dropdownRef" class="relative">
    <button class="flex items-center focus:outline-none" @mouseenter="open">
      <slot name="title" />
    </button>
    <ul
      v-if="isOpen"
      class="absolute p-2 left-0 mt-2 min-w-40 w-max z-[calc(1e12)] bg-white border border-gray-200 rounded shadow-lg"
      @mouseleave="close"
      @click="close"
    >
      <slot />
    </ul>
  </div>
</template>

<style scoped>
@reference "../../main.css";

ul > li {
  @apply font-semibold flex flex-row gap-x-1 items-center px-4 py-2 hover:bg-gray-100;
}
</style>
